/* 
Problem: 002
Author: Milan Capoor
Date: 3 June 2019
*/ 

//PROBLEM 2: Even Fibonacci Numbers
/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int fibonacci(int max) {
    int old = 0;
    int previous = 1;
    int current = 2;
    int sum = 2; //not summed in first loop

    while (current <= max) { //values that do not exceed 4 000 000
        //the index of each term is decreased as it is used, replaced with newer values
        old = previous; //the old 'previous' value is now the 'old' value
        previous = current; //the old 'current' value is now the 'previous' value
        current = previous + old; //the value of the next term is the sum of the previous two
        
        if (current % 2 == 0) { //even values
            sum += current; //the sum
        }
    }
    return sum;
}

int main() {
    int max = 4000000; //the upper bound
    printf("The sum of the even fibonacci numbers less than max is: %d\n", fibonacci(max));
    return 0;
}